-- MySQL Script generated by MySQL Workbench
-- Sáb 24 Out 2015 17:31:08 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SchoolProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SchoolProject` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SchoolProject` ;

-- -----------------------------------------------------
-- Table `SchoolProject`.`discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`discipline` (
  `discipline_id` INT(11) NOT NULL,
  `name_discipline` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`discipline_id`))
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SchoolProject`.`module`
-- ---------------------------------------rol_id--------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`module` (
  `module_id` INT(11) NOT NULL,
  `module_name` VARCHAR(45) NOT NULL,
  `discipline_discipline_id` INT(11) NOT NULL,
  PRIMARY KEY (`module_id`),
  CONSTRAINT `fk_module_discipline1`
    FOREIGN KEY (`discipline_discipline_id`)
    REFERENCES `SchoolProject`.`discipline` (`discipline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SchoolProject`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`course` (
  `cuurse_id` INT(11) NOT NULL,
  `course_name` VARCHAR(45) NOT NULL,
  `begin_hour` TIME NOT NULL,
  `end_hour` TIME NOT NULL,
  `course_duration` INT(11) NOT NULL,
  `module_module_id` INT(11) NOT NULL,
  PRIMARY KEY (`cuurse_id`),
  CONSTRAINT `fk_course_module1`
    FOREIGN KEY (`module_module_id`)
    REFERENCES `SchoolProject`.`module` (`module_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SchoolProject`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`role` (
  `rol_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rol_name` VARCHAR(255) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`rol_id`))
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SchoolProject`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`user` (
  `userid` INT(11) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `role_rol_id` INT(11) NOT NULL,
  PRIMARY KEY (`userid`),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_rol_id`)
    REFERENCES `SchoolProject`.`role` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SchoolProject`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`teacher` (
  `teacher_id` INT(11) NOT NULL,
  `user_userid` INT(11) NOT NULL,
  PRIMARY KEY (`teacher_id`),
  CONSTRAINT `fk_teacher_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `SchoolProject`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SchoolProject`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`student` (
  `student_id` INT(11) NOT NULL,
  `user_userid` INT(11) NOT NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `fk_student_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `SchoolProject`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `SchoolProject`.`class_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`class_room` (
  `clrm_id` INT(11) NOT NULL,
  `class_room_name` VARCHAR(45) NOT NULL,
  `module_module_id` INT(11) NOT NULL,
  `discipline_discipline_id` INT(11) NOT NULL,
  PRIMARY KEY (`clrm_id`),
  CONSTRAINT `fk_class_room_module1`
    FOREIGN KEY (`module_module_id`)
    REFERENCES `SchoolProject`.`module` (`module_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_room_discipline1`
    FOREIGN KEY (`discipline_discipline_id`)
    REFERENCES `SchoolProject`.`discipline` (`discipline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SchoolProject`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`schedule` (
  `schedule_id` INT(11) NOT NULL,
  `week_day` VARCHAR(45) NOT NULL,
  `begin_hour` TIME NOT NULL,
  `end_hour` VARCHAR(45) NOT NULL,
  `discipline_discipline_id` INT(11) NOT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `fk_schedule_discipline1_idx` (`discipline_discipline_id` ASC),
  CONSTRAINT `fk_schedule_discipline1`
    FOREIGN KEY (`discipline_discipline_id`)
    REFERENCES `SchoolProject`.`discipline` (`discipline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `SchoolProject`.`privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`privilege` (
  `pri_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pri_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`pri_id`))
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SchoolProject`.`student_class_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`student_class_room` (
  `student_classroom_id` int(11) NOT NULL AUTO_INCREMENT,
  `student_student_id` INT(11) NOT NULL,
  `class_room_clrm_id` INT(11) NOT NULL,
  PRIMARY KEY (`student_classroom_id`),
  CONSTRAINT `fk_student_has_class_room1_student1`
    FOREIGN KEY (`student_student_id`)
    REFERENCES `SchoolProject`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_class_room1_class_room1`
    FOREIGN KEY (`class_room_clrm_id`)
    REFERENCES `SchoolProject`.`class_room` (`clrm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `SchoolProject`.`teacher_class_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`teacher_class_room` (
  `teacher_class_room_id` int(11) NOT NULL AUTO_INCREMENT,
  `teacher_teacher_id` INT(11) NOT NULL,
  `class_room_clrm_id` INT(11) NOT NULL,
  PRIMARY KEY (`teacher_class_room_id`),
  CONSTRAINT `fk_teacher_has_class_room1_teacher1`
    FOREIGN KEY (`teacher_teacher_id`)
    REFERENCES `SchoolProject`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacher_has_class_room1_class_room1`
    FOREIGN KEY (`class_room_clrm_id`)
    REFERENCES `SchoolProject`.`class_room` (`clrm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `SchoolProject`.`role_privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolProject`.`role_privilege` (
  `rolPriId` INT(11) NOT NULL AUTO_INCREMENT,
  `rol_id` INT(11) NOT NULL,
  `pri_id` INT(11) NOT NULL,
  PRIMARY KEY (`rolPriId`),
  INDEX `fk_role_id` (`rol_id` ASC),
  INDEX `fk_pri_id` (`pri_id` ASC),
  CONSTRAINT `fk_pri_id`
    FOREIGN KEY (`pri_id`)
    REFERENCES `SchoolProject`.`privilege` (`pri_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`rol_id`)
    REFERENCES `SchoolProject`.`role` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;